In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np
import pandas as pd
from pybaseball import lahman

In [3]:
##reads in batting csv file
batting = pd.read_csv('C:/Users/Andrew Fish/Documents/Baseball Data/baseballdatabank-2023.1/core/Batting.csv')
##will use OBP, HR, R, RBI, SB as those are the hitting statistics used in my rotisserie fantasy baseball league
##adding obp since all the others are in the batting data frame already
batting['OBP'] = ((batting['H'] + batting['BB'] + batting['HBP']) / 
                  (batting['AB'] + batting['BB'] + batting['SF'] + batting ['HBP']))
##creates data frame with desired stats
batter_ranks = pd.DataFrame({'Season' : batting['yearID'],
                             'OBP' : batting['OBP'],
                             'HR' : batting['HR'],
                             'R' : batting['R'],
                             'RBI' : batting['RBI'],
                             'SB' : batting['SB']})
##creates index as player id and then fills na to 0
batter_ranks.index = batting['playerID']
batter_ranks = batter_ranks.fillna(0)

In [4]:
##adding ranks for each stat
batter_ranks['OBP_rank'] = batter_ranks.OBP.rank(ascending = False)
batter_ranks['HR_rank'] = batter_ranks.HR.rank(ascending = False)
batter_ranks['R_rank'] = batter_ranks.R.rank(ascending = False)
batter_ranks['RBI_rank'] = batter_ranks.RBI.rank(ascending = False)
batter_ranks['SB_rank'] = batter_ranks.SB.rank(ascending = False)
##sums all the individual ranks then it ranks them
batter_ranks['Overall_rank'] = (batter_ranks.OBP_rank + batter_ranks.HR_rank + batter_ranks.R_rank +
                                batter_ranks.RBI_rank + batter_ranks.SB_rank).rank(method = 'first')
##sorts by overall rank
batter_ranks = batter_ranks.sort_values(by = 'Overall_rank')
##gives the top 10 players by overall rank
batter_ranks.head(10)

,Season,OBP,HR,R,RBI,SB,OBP_rank,HR_rank,R_rank,RBI_rank,SB_rank,Overall_rank
playerID,,,,,,,,,,,,
bondsba01,1996,0.460741,42,122,129.0,40.0,1848.0,228.5,462.5,236.5,924.0,1.0
walkela01,1997,0.451807,49,143,130.0,33.0,1919.0,56.5,85.0,216.0,1537.0,2.0
bagweje01,1999,0.454047,42,143,126.0,30.0,1902.0,228.5,85.0,301.5,1932.0,3.0
bondsba01,1993,0.458457,46,129,123.0,29.0,1859.0,118.0,276.5,391.0,2089.5,4.0
burksel01,1996,0.407625,40,142,128.0,32.0,3019.0,324.0,93.0,255.0,1653.0,5.0
bondsba01,1997,0.446377,40,123,101.0,37.0,1972.0,324.0,423.0,1778.5,1137.0,6.0
rodrial01,2007,0.422316,54,143,156.0,24.0,2472.0,23.0,85.0,29.5,3038.5,7.0
bagweje01,1997,0.425384,43,109,135.0,31.0,2407.0,194.5,1209.5,159.0,1780.0,8.0
bondsba01,1998,0.438218,37,120,122.0,28.0,2103.0,519.5,555.0,426.0,2237.5,9.0
morgajo02,1976,0.444073,27,113,111.0,60.0,2045.0,1931.5,922.0,914.0,227.5,10.0